version: '3.3'
services:
  arangodb:
    image: arangodb:3.5.0
    network_mode: bridge
    environment:
      ARANGO_ROOT_PASSWORD: root
    ports:
      - 8529:8529

  service-manager:
    image: mds-docker-ci-dev.artifactory.globalrelay.net/mock-service-manager:1.0.0.c964c76
    network_mode: bridge
    ports:
     - 8083:8080

  session-service:
    image: mds-docker-ci-dev.artifactory.globalrelay.net/mock-session-service:1.0.0.f516482
    network_mode: bridge
    ports:
      - 8082:8080

  mds:
    image: mds-docker-ci-dev.artifactory.globalrelay.net/mock-mds:1.0.0.5b47753
    volumes:
     - ./mds.properties:/app/mock-mds/mock-mds.properties
    network_mode: bridge
    ports:
     - 8441:8441

  smtp-service:
    image: mds-docker-ci-dev.artifactory.globalrelay.net/mock-smtp-service:1.0.0.fd89779
    network_mode: bridge
    ports:
      - 8442:8442
      - 2525:2525

  mps:
    #image: docker-repo.globalrelay.net/provisioning-server:1.0.0
    build:
      context: ./provisioning-server
      args:
        - BUILD_FINAL_NAME=provisioning-server-1.0.0.0f28c2a
    volumes:
      - ./mps.properties:/app/provisioning/conf/provisioning-server.properties
    network_mode: bridge
    ports:
      - 8081:8081
      - 5008:5008
